name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on:
      ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm install
      - name: Build production project
        run: npm run build:prod
        if: always()
      - name: Lint typescript
        run: npm run lint:ts
        if: always()
      - name: Lint scss
        run: npm run lint:scss
        if: always()
      - name: Run unit tests
        run: npm run test:unit
        if: always()
      - name: Build storybook
        run: npm run storybook:build
        if: always()
      - name: Run screenshot tests
        run: npm run test:ui:ci